### ISSUE TITLE
removeUser does not commit the change

### ISSUE THREAD

**Issue by ernpal** [jhuertero/oopProject#3]
Removing a user via the UserManagementForm reports that the user was successfully removed.

This appears to be true for the in-memory dataset, because (1) attempting to remove the user a second time reports the user does not exist and (2) the same user ID can be re-added to the system.

However, when ApplicationServer is restarted the removed user is reloaded.

**Comment by jhuertero** [comment]
Fix for this is for there to be a call from the login form to the server to serialize both files when the form is closing.

**Comment by ernpal** [comment]
I'm tweaking the LoginForm, now, on the dev-Login branch.  I'll try to implement your proposed fix, while I am it.

**Comment by sishirsubedi** [comment]
Hi Jose,

I am working on the check in /check out on transaction form.

Since we have to link user to the device and record which user has which
device, did you plan anything while creating this design. Let me know, I am
trying to add devicehandler for  user which manages its devices.
